name: document_picker
description: Flutter plugin to pick, capture images or add signature in your form
version: 0.0.1
homepage: https://github.com/muhammadmateen027/document_picker

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0 <2.0.0"

dependencies:
  dotted_border: ^1.0.6
  flutter:
    sdk: flutter
  image_picker: ^0.6.7+10
  path_provider: ^1.6.16
  permission_handler: ^5.0.1+1
  signature: ^3.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - assets/images/